version: "3.9"

networks:
  lms:
    name: lms
    enable_ipv6: false


services:
  gateway:
    build: ./docker/gateway
    volumes:
      - ./docker/gateway/config/conf.d:/etc/nginx/conf.d
      - ./docker/app/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - lms

  queue:
    build:
      context: ./docker/app
      dockerfile: queue.Dockerfile
    volumes:
      - ./moodle:/app:delegated
      - ./data:/data
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      IS_DOCKER: 'yes'
    networks:
      - lms

  app:
    build: ./docker/app
    hostname: backend
    volumes:
      - ./moodle:/app:delegated
      - ./docker/app/nginx/config/conf.d:/etc/nginx/conf.d
      - ./docker/app/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./data:/data
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      IS_DOCKER: 'yes'
    networks:
      - lms

  mysql:
    hostname: db
    build: ./docker/db
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/files:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mdl
    ports:
      - "3310:3306"
    networks:
      - lms

  keydb:
    image: eqalpha/keydb:x86_64_v5.3.3
    hostname: redis
    # command: keydb-server /etc/keydb/redis.conf --server-threads 2 --active-replica yes --replicaof 192.168.1.1 6379
    # command: keydb-server /etc/keydb/redis.conf --server-threads 2 --active-replica yes --replicaof 192.168.1.2 6379
    command: keydb-server /etc/keydb/redis.conf --server-threads 2
    volumes:
      - ./docker/app/redis.conf:/etc/keydb/redis.conf
      - data:/data
    restart: unless-stopped
    networks:
      - lms

volumes:
  data:
    driver: local